### PR TITLE
update id/remove dup. plugin.json

### PR DESCRIPTION
**Pull request by sjoeboo**
to align w/ the id we're publishing the plugin with.

### CODE REVIEW

**Comment by dmichel1** [comment]
can we change the publishing id to align with the name of the repo/existing id? if possible i don't think we should publish it with the Spotify name - it should remain agnostic.

**Comment by sjoeboo** [comment]
hm, i can ask, but looking @ other plugins it seems generally most have the `org` name IN the plugin id. I think it IS agnostic, just as agnostic as any other plugin some org/user makes "matts-custom-plugin", etc etc.

**Comment by dmichel1** [comment]
@sjoeboo how are the one for prometheus and influx named? if we split heroic into it's own github org because we got it in to CNCF sandbox calling it spotify-* would be strange.

**Comment by sjoeboo** [comment]
influx is under the grafana org. so its grafana-influxdb-datasource. I think prom is built in, as the only one in the repo is "camptocamp-prometheus-alertmanager-datasource"

**Comment by sjoeboo** [comment]
https://github.com/grafana/grafana-plugin-repository/blob/9016a4faab0bf9acb77c839e894fe1be229528dd/repo.json is the repo FYI.

**Comment by sjoeboo** [comment]
I think if we moved heroic into its own org @ somepoint, we'd change the plugin name/id to follow it.

**Comment by dmichel1** [comment]
closed by https://github.com/spotify/heroic-grafana-datasource/pull/84

**Pull request closed without merging**
